name: Greet Everyone
on:
  repository_dispatch:
    types: [riffraff]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: Update commit status # You would run your tests before this using the output to set state/desc
        if: ${{ success() }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'RiffRaff Deploy'
          description: 'BUILD_ID'
          state: 'success'
          target_url: "https://github.com/guardian/riffraff-github-action-trigger/actions"
          sha: ${{ github.event.client_payload.ref }}
      - name: Update commit status # You would run your tests before this using the output to set state/desc
        if: ${{ failure() }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'RiffRaff Deploy'
          description: 'BUILD_ID'
          state: 'failure'
          sha: ${{ github.event.client_payload.ref }}
